#pragma once
#ifndef SAM_HPP
#define SAM_HPP

// #include "tiny_adflex.hpp"
#include "SAM_preprocessor.h"
#include "SAM/logspace.hpp"
#include "SAM/newton.hpp"
#include "SAM/pnorm.hpp"
#include "SAM/convenience.hpp"
#include "SAM/spline.hpp"
#include "SAM/define.hpp"
#include "SAM/refpointset.hpp"
#include "SAM/mvmix.hpp"
#include "SAM/incidence.hpp"
#include "SAM/recruitment.hpp"
#include "SAM/hcr.hpp"
#include "SAM/extend_array.hpp"
#include "SAM/predn.hpp"
#include "SAM/predf.hpp"
#include "SAM/equilibrium_recycling.hpp"
#include "SAM/equilibrium.hpp"
#include "SAM/stochastic_equilibrium.hpp"
#include "SAM/toF.hpp"
#include "SAM/forecast.hpp"
#include "SAM/season.hpp"
#include "SAM/survival.hpp"
#include "SAM/biopar.hpp"
#include "SAM/p.hpp"
#include "SAM/derived.hpp"
#include "SAM/f.hpp"
#include "SAM/reproductive.hpp"
#include "SAM/n.hpp"
#include "SAM/forecastsim.hpp"
#include "SAM/predobs.hpp"
#include "SAM/obs.hpp"
#include "SAM/referencepoints.hpp"
#include "SAM/splinePenalty.hpp"

#endif
